angular.module("mainApp")
.service("itemTypeService",function($http){
	var service ={
		filterdItemResults:{},
		categoryList : [
			{"categoryName" : "Electronics", "selected" : true},
			{"categoryName" : "Clothes", "selected" : false},
			{"categoryName" : "Shoes", "selected" : false},
			{"categoryName" : "Bag", "selected" : false},
			{"categoryName" : "Perfumes", "selected" : false},
			{"categoryName" : "Furniture", "selected" : false},
			{"categoryName" : "Others", "selected" : false},
		],
		
		electronicsList : [ 
	            {"subCategoryName":"Phone","selected":false},
	            {"subCategoryName":"Laptop","selected":false},
	            {"subCategoryName":"Monitor","selected":false},
	            {"subCategoryName":"Desktop","selected":false},
	            {"subCategoryName":"Printer","selected":false},
	            {"subCategoryName":"Scanner","selected":false},
	            {"subCategoryName":"Camera","selected":false},
	            {"subCategoryName":"Bluetooth Headphone","selected":false},
	            {"subCategoryName":"Bluetooth Speaker","selected":false},
	            {"subCategoryName":"Playstation","selected":false},
	            {"subCategoryName":"X-Box","selected":false},
	            {"subCategoryName":"Computer Accessories","selected":false},		                
		],
		clothingList : [ 
		                {"subCategoryName":"Jeans","selected":false},
		 	            {"subCategoryName":"Tshirt","selected":false},
		 	            {"subCategoryName":"Pants","selected":false},
			            {"subCategoryName":"Shirt","selected":false},
			            {"subCategoryName":"Tie","selected":false},
			            {"subCategoryName":"Sorts","selected":false},
			            {"subCategoryName":"Jackets","selected":false},
			            {"subCategoryName":"Suits","selected":false},
			            {"subCategoryName":" Sweaters","selected":false},		                
				],
		shoesList : [ 
		                {"subCategoryName":"Chukkas","selected":false},
		 	            {"subCategoryName":"Loafers","selected":false},
		 	            {"subCategoryName":"Work Boots","selected":false},
			            {"subCategoryName":"Dress Boots","selected":false},
			            {"subCategoryName":"Duck Boots","selected":false},
			            {"subCategoryName":"Gym Sneakers","selected":false},
			            {"subCategoryName":"Casual Street Sneakers","selected":false},
			            {"subCategoryName":"Flip-Flops","selected":false},
			            {"subCategoryName":" Slippers","selected":false},		
			            {"subCategoryName":" Dress shoes","selected":false},
				],
		bagList : [ 
		                {"subCategoryName":"Jeans","selected":false},
		 	            {"subCategoryName":"Tshirt","selected":false},
		 	            {"subCategoryName":"Pants","selected":false},
			            {"subCategoryName":"Shirt","selected":false},
			            {"subCategoryName":"Tie","selected":false},
			            {"subCategoryName":"Sorts","selected":false},
			            {"subCategoryName":"Jackets","selected":false},
			            {"subCategoryName":"Suits","selected":false},
			            {"subCategoryName":" Sweaters","selected":false},		                
					],
		perfumesList : [ 
		                {"subCategoryName":"Anna Sui","selected":false},
			            {"subCategoryName":"Johann Maria Farina	","selected":false},
			            {"subCategoryName":"Caswell-Massey","selected":false},
			            {"subCategoryName":"Parfums Lubin ","selected":false},
			            {"subCategoryName":"4711","selected":false},
			            {"subCategoryName":"Roger & Gallet","selected":false},
			            {"subCategoryName":"Truefitt & Hill","selected":false},
			            {"subCategoryName":"Floris of London","selected":false},
			            {"subCategoryName":" Creed","selected":false},
		                {"subCategoryName":"Guerlain","selected":false},
			            {"subCategoryName":"Penhaligon's","selected":false},
			            {"subCategoryName":"Houbigant","selected":false},
			            {"subCategoryName":"Lenthéric","selected":false},
			            {"subCategoryName":"Ed. Pinaud","selected":false},
			            {"subCategoryName":"Coty, Paris","selected":false},
			            {"subCategoryName":"Caron","selected":false},
			            {"subCategoryName":"Rigaud","selected":false},
			            {"subCategoryName":"Yardley	","selected":false},
		                {"subCategoryName":"Chanel	","selected":false},
		 	            {"subCategoryName":"Lanvin","selected":false},
		 	            {"subCategoryName":"Bourjois","selected":false},
			            {"subCategoryName":"Jean Patou","selected":false},
			            {"subCategoryName":"Worth","selected":false},
			            {"subCategoryName":"Dana","selected":false},
			            {"subCategoryName":"Elizabeth Arden","selected":false},
			            {"subCategoryName":"Alfred Dunhill	","selected":false},
			            {"subCategoryName":" Caron	","selected":false},	
			],
												
		furnitureList : [ 
		                {"subCategoryName":"Couches","selected":false},
				        {"subCategoryName":"Dinning Tables","selected":false},
				        {"subCategoryName":"Bed","selected":false},
				        {"subCategoryName":"Coffee Tables","selected":false},
				        {"subCategoryName":"Chairs","selected":false},
				        {"subCategoryName":"Ottomans","selected":false},
				        {"subCategoryName":"Recliners","selected":false},
				        {"subCategoryName":"Loveseats","selected":false},
				        {"subCategoryName":"Sleepers","selected":false},		
		                {"subCategoryName":"Couches","selected":false},
				        {"subCategoryName":"Dinning Tables","selected":false},
				        {"subCategoryName":"Bed","selected":false},
				        {"subCategoryName":"Coffee Tables","selected":false},
				        {"subCategoryName":"Chairs","selected":false},
				        {"subCategoryName":"Ottomans","selected":false},
				        {"subCategoryName":"Recliners","selected":false},
				        {"subCategoryName":"Loveseats","selected":false},
				        {"subCategoryName":"Sleepers","selected":false},
		                {"subCategoryName":"Couches","selected":false},
				        {"subCategoryName":"Dinning Tables","selected":false},
				        {"subCategoryName":"Bed","selected":false},
				        {"subCategoryName":"Coffee Tables","selected":false},
				        {"subCategoryName":"Chairs","selected":false},
				        {"subCategoryName":"Ottomans","selected":false},
				        {"subCategoryName":"Recliners","selected":false},
				        {"subCategoryName":"Loveseats","selected":false},
				        {"subCategoryName":"Sleepers","selected":false},
		],
		otherList : [ 
		                {"subCategoryName":"Vechiles","selected":false},
		 	            {"subCategoryName":"Sports","selected":false},
		 	            {"subCategoryName":"Gardening","selected":false},
			            {"subCategoryName":"Guitar","selected":false},
			            {"subCategoryName":"Kitchen Items","selected":false},
			            {"subCategoryName":"Bathroom Items","selected":false},
			            {"subCategoryName":"Books","selected":false},
			            {"subCategoryName":"Candels","selected":false},
			            {"subCategoryName":"Lamps","selected":false},		                
				],
		
	}
	return service;
})